### ISSUE TITLE
Purpose of buildDependencies?

### ISSUE THREAD

**Issue by luii** [piranna/buildDependencies#3]
Looking at the source i would say in the context of NodeOS it installs all dependencies that are in devDependencies with the corresponding value in `buildDependencies` when using the production flag? Is this quite right?

**Comment by piranna** [comment]
Yes, that's it. Idea is that `dependencies` has just only the needed ones to install the modules, just the basis to download the prebuild images. If that step fails and module needs to be build and compiled, then `buildDependencies` download the dependencies needed to build the module, like `nan` and similar ones. This way, since they are defined in the `devDependencies` field, they can be check by greenkeeper so they get updated too.

**Comment by luii** [comment]
Got it now! Thanks!

**Comment by piranna** [comment]
You are welcome :-) Sorry to be so much offline, during last months I have been very busy at work and I'm still trying to retake things.

**Comment by luii** [comment]
Yeah i noticed it, thought that you have no more interest in NodeOS.
Im still trying to get nodegit to work with NodeOS, i've also got it to compile 
with static libs but it says that i have to set the host flag which is obviously set on configure...

looked at your code on `nodeos-nodejs`
```bash
    CC=$TARGET-gcc               \
    CXX=$TARGET-g++              \
    $SRC_DIR/configure           \
        --prefix=$OUT_DIR        \
        --dest-cpu=$NODE_ARCH    \
        --dest-os=$NODE_PLATFORM \
        --without-dtrace         \
        --without-intl           \
        --without-npm            \
--without-snapshot || exit 8
```

does it makes a difference if i dont put backslashes on the first env variables `(CC=... \` and `CXX=... \`)?

**Comment by piranna** [comment]
> Yeah i noticed it, thought that you have no more interest in NodeOS.

If you are interested I can give you administrator permissions in the org and npm and SemaphoreCI, since seems you have more time to work on this :-) @groundwater once gave me the project, it would not be bad to pass it again to another interested person :-)


> does it makes a difference if i dont put backslashes on the first env variables (CC=... \ and CXX=... \)?

Backslashes are just only to "escape" the newline, so bash find the command as if it were written in a single line. It's just for aesthetics and make code more readable, they should not affect how it's executed. If you need the host, just check the output of `./configure --help` to know what's the correct flag and add it.
